<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Identity.Application\" />
      <Folder Include="Identity.Contracts\" />
      <Folder Include="Identity.Domain\" />
      <Folder Include="Identity.Infrastructure\" />
    </ItemGroup>

</Project>
